config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'posts#index'

  resources :posts do
    resources :comments, only: [:new, :create]
  end

  
    resources :bios
  

  resources :users do
    resources :comments, only: [:new, :create]
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :bio, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user! 
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fist_name, :last_name])
  end

end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  # before_action :set_bio, only: [:update, :edit, :show]
  
  def index
   
  end

  def create
    @bio = Bio.new(bio_params)
    @bio.user_id = current_user.id
    if @bio.save
      redirect_to bio_path([:id])
    else
      render partial: "form"
    end
  end

  def update
    @bio = Bio.find(params[:id])
    @bio.user_id = current_user.id
    if @bio.update(bio_params)
      redirect_to @bio
    else
      redirect :edit
    end
  end

  def destroy
  end

  def show
    @user = current_user
    @bio = Bio.find(params[:id])
  end

  def edit
    @bio = Bio.find(params[:id])
    @bio.user_id = current_user.id
    render partial: "form"
  end

  def new
    @bio = Bio.new
    render partial: "form"
  end

  private
  def bio_params
    params.require(:bio).permit(:profile_image, :description)
  end

  def set_bio
    @bio = current_user.bios.find(params[:bio_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_user
  
  def new
    @comment = Comment.new
    render partial: "form"
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to post_path(@post)
    else
      render partial: "form"
    end
  end

private

def set_user
  @user = current_user
end

def set_post
  @post = current_user.posts.find(params[:post_id])
end

def comment_params
  params.require(:comment).permit(:message)
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_user, only: [:create]
  before_action :set_posts, only: [:show, :update, :edit, :destroy]
  
  def index
    @posts = Post.all
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render partial: "form"
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      redirect :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def show
  end

  def edit
    render partial: "form"
  end

  def new
    @post = Post.new
    render partial: "form"
  end

private

def set_user
  @user = User.find(params[:user_id])
end

def set_posts
  @post = Post.find(params[:id])
end

def post_params
  params.require(:post).permit(:content)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/bios/_form.html.erb
<h1>Edit Profile</h1>
<hr/>
<%= form_for [@bio] do |f| %>
  <%= f.label :profile_image %>
  <%= f.text_area :profile_image, required: true, autofocus: true %>
  <%= f.label :description %>
  <%= f.text_area :description, required: true %>
  <%= f.submit %>
  <% end %>

app/views/bios/create.html.erb
<h1>Bios#create</h1>
<p>Find me in app/views/bios/create.html.erb</p>

app/views/bios/destroy.html.erb
<h1>Bios#destroy</h1>
<p>Find me in app/views/bios/destroy.html.erb</p>

app/views/bios/edit.html.erb
<h1>Bios#edit</h1>
<p>Find me in app/views/bios/edit.html.erb</p>

app/views/bios/index.html.erb
<h1>Bios#index</h1>
<p>Find me in app/views/bios/index.html.erb</p>

app/views/bios/new.html.erb
<h1>Bios#new</h1>
<p>Find me in app/views/bios/new.html.erb</p>

app/views/bios/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %>
<br/>

<h1><%= @bio.profile_image %></h1>

<br/>

<h1><%= @bio.description %>

<br/>


<h3><%= link_to 'Create Profile', new_bio_path %>
<h3><%= link_to 'Edit Profile', edit_bio_path(@user) %></h3>

app/views/bios/update.html.erb
<h1>Bios#update</h1>
<p>Find me in app/views/bios/update.html.erb</p>

app/views/comments/_comment.html.erb
<hr/>
<p><%=comment.message %></p>
<hr/>

app/views/comments/_form.html.erb
<h1>Write a Comment</h1>
<hr/>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :message %>
  <%= f.text_area :message, required: true, autofocus: true %>
  <%= f.submit %>
  <% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= button_to 'Log Out', destroy_user_session_path, method: :delete %>
  <hr/>
  <%= link_to 'Home', root_path %>
  <%= link_to 'New Twitter Post', new_post_path %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<h1><%= @post.id ? 'Edit Post' : 'Create Post' %></h1>
<hr/>
<%= form_for @post do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content, required: true, autofocus: true %>
  <%= f.submit %>
  <% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<div id="box"><h1>Welcome <%= current_user.first_name %> </h1>
<br/>
<%= link_to 'Profile Page', bio_path(:id) %>
<h2> Please select a post </h2>

<%= link_to 'Create new post', new_post_path %>

<hr/>

<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.content, post_path(post) %></li>
    <%= link_to 'Edit Post', edit_post_path(post) %>
    <%= link_to 'Delete', post_path(post), method: :delete %>
    <br/>
    <hr/>
    <% end %>
</ul>

</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1><%=@post.content%></h1>
<br/>
<br/>
<%= link_to 'Edit Post', edit_post_path(@post) %>
<%= link_to 'Delete Post', post_path(@post), method: :destroy %>
<%= link_to 'Add Comment', new_post_comment_path(@post.id) %>
<hr/>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
<%= render 'comments/comment', {comment: comment} %>
<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>